jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/library_ssm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
jdbc.username=root
jdbc.password=zyj2005!
jdbc.initialSize=5
jdbc.maxActive=50
jdbc.minIdle=5
jdbc.maxWait=3000
